# Generated by Django 5.1.1 on 2024-10-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_no', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('bank', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('cnic', models.CharField(max_length=15)),
                ('contact_no', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=50)),
                ('covid_vaccinated', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('date_of_rejoining', models.DateField(blank=True, null=True)),
                ('date_of_resignation', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_status', models.CharField(max_length=20)),
                ('father_cnic', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('martial_status', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('province', models.CharField(max_length=50)),
                ('wing', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
